server:
    port: 8080

spring:
    application:
        name: potato

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/wallet
        username: postgres
        password: postgres

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: false
        open-in-view: false