server:
    port: 8080

spring:
    datasource:
        # По умолчанию postgresql имеет 5432 порт. Но так как подразумевается запуск через docker-compose, указан порт
        # из docker-compose.yaml для корректной проброски. Если у вас локально установлен postgresql и вы собираетесь
        # использовать его, то требуется поменить его на нужный
        url: jdbc:postgresql://localhost:5432/wallet
        username: postgres
        password: postgres
    flyway:
        enabled: true
        locations:
          - db.migration
        baseline-on-migrate: true
    jpa:
        show-sql: false
        properties:
          hibernate:
              format_sql: true
