server:
    port: 8080

spring:
    application:
        name: potato

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://database:5430/walletDB
        username: postgres
        password: postgres

    jpa:
        properties:
            hibernate:
                default_schema: public
                format_sql: true
        show_sql: true
        hibernate:
            ddl-auto: none
        open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect