drop table users;

create table users (
                       id uuid primary key not null ,
                       first_name varchar(50) not null ,
                       second_name varchar(50) not null ,
                       phone varchar(11) not null unique ,
                       email varchar(50) not null unique ,
                       birthdate date not null ,
                       password varchar(255) not null ,
                       role varchar(20) not null
);

delete from users where phone='77777777778';

create table session (
                         id uuid not null ,
                         created_at timestamp without time zone not null ,
                         modified_at timestamp without time zone ,
                         access_token varchar(400) not null ,
                         refresh_token varchar(400) not null ,
                         enabled boolean not null,
                         user_id uuid not null references users("id")
);

drop table wallets;
create table wallets (
                         id int primary key generated by default as identity ,
                         balance int not null ,
                         user_id uuid not null references users("id")
);

alter table wallets
add constraint user_id_constraint
foreign key (user_id) references users(id) on delete cascade